#!/usr/bin/bash
#
# Generate a CF Manifest - this is a horrible process.
# http://docs.cloudfoundry.org/deploying/openstack/cf-stub.html
# Joey

# This needs to be setup already.
# Bind entries looks like this:
# *.cf.domain.com                     IN      A               1.2.3.4

echo "Generating CF manifest."

# Put all your constants in this file
source env.local

log="/tmp/cfmanifest.log"
echo "" > $log

ip=$(nova list|grep cf-management|perl -lane 'print $1 if (/public=(.*?)\s/)')
login="ssh -i /root/.ssh/cf_id_rsa $ip"

echo -n "Getting Bosh UUID: "
DIRECTOR_UUID=$($login 'bosh status --uuid')
echo "Ok ($DIRECTOR_UUID)"

echo -n "Getting CF Release Version: "
login="ssh -i /root/.ssh/cf_id_rsa $ip"
CF_RELEASE=$($login "bosh releases 2>&1| grep cf|awk '{print \$4}'|sed 's/[^0-9]*//g'")
echo "Ok ($CF_RELEASE)"

# Get a floater for HAPROXY
echo -n "Creating floating IP for HAProxy: "
net=$(ifconfig br1 | perl -lane 'print $1 if /inet (.*?)\s/' | cut -d'.' -f1-3);
HAPROXY="$net.111"
neutron floatingip-create --floating-ip-address $HAPROXY public &>> /dev/null
echo "OK ($HAPROXY)"

function pw_hash() {
   strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 10 | tr -d '\n'; echo
}

function keygen() {

   key=$1
   echo "Generating RSA key for: $key"
   ssh-keygen -N '' -f keys/${key}_id_rsa &> /dev/null
}

function cert_gen() {

   app=$1
   echo "Creating a cert for: $app"
   co=US; st=Colorado; loc=Boulder; org=CF; orgu=IT; comname=$DOMAIN; email=nobody@cf.com
   openssl genrsa -out certs/pk_$app.pem 2048 &>> $log
   openssl req -new -key certs/pk_$app.pem -out certs/csr_$app.pem \
       -subj "/C=$co/ST=$st/L=$loc/O=$org/OU=$orgu/CN=$comname/emailAddress=$email" &>> $log
   openssl x509 -req -days 2048 -in certs/csr_$app.pem -signkey certs/pk_$app.pem -out certs/cert_$app.pem &>> $log
}

function cert_cat() {

   file=$1
   cat $file|perl -lane '$_ =~ s/^\s+//; print "          $_"'
}

# We need a bunch of random passwords
DB_ENCRYPTION_KEY=$(pw_hash)
STAGING_UPLOAD_PASSWORD=$(pw_hash)
BULK_API_PASSWORD=$(pw_hash)
BLOBSTORE_PASSWORD=$(pw_hash)
NATS_PASSWORD=$(pw_hash)
ROUTER_PASSWORD=$(pw_hash)
CCDB_PASSWORD=$(pw_hash)
UAADB_PASSWORD=$(pw_hash)
CCDB_PASSWORD=$(pw_hash)
UAADB_PASSWORD=$(pw_hash)
CONSUL_ENCRYPT_KEY=$(pw_hash)
LOGGREGATOR_PASSWORD=$(pw_hash)
ROUTER_PASSWORD=$(pw_hash)
ADMIN_SECRET=$(pw_hash)
ADMIN_PASSWORD=$(pw_hash)
CC_CLIENT_SECRET=$(pw_hash)
CC_ROUTING_SECRET=$(pw_hash)
CC_LOOKUP_SECRET=$(pw_hash)
DOPPLER_SECRET=$(pw_hash)
GOROUTER_SECRET=$(pw_hash)
TCP_EMITTER_SECRET=$(pw_hash)
TCP_ROUTER_SECRET=$(pw_hash)
LOGIN_CLIENT_SECRET=$(pw_hash)
N_CLIENT_SECRET=$(pw_hash)

# Set some values for stuff we know about.
PUBLIC_NET=$(neutron net-list|grep public | awk '{print $2}')
PRIVATE_NET=$(neutron net-list|grep cf-private | awk '{print $2}')
ENVIRONMENT=$(hostname)

for dir in key certs; do
   if [ ! -d $dir ]; then
      rm -rf $dir
      mkdir $dir
   fi
done

cert_gen blobstore
BLOBSTORE_TLS_CERT=$(cert_cat certs/cert_blobstore.pem)
BLOBSTORE_PRIVATE_KEY=$(cert_cat certs/pk_blobstore.pem)

cert_gen haproxy
HAPROXY_TLS_CERT=$(cert_cat certs/cert_haproxy.pem)
HAPROXY_PRIVATE_KEY=$(cert_cat certs/pk_haproxy.pem)

# Consul certs/keys (generated by cf_deploy_on_openstack.sh)
CONSUL_CA_CERT=$(cert_cat cf-release/consul-certs/consulCA.crt)
CONSUL_SERVER_CERT=$(cert_cat cf-release/consul-certs/server.crt)
CONSUL_SERVER_KEY=$(cert_cat cf-release/consul-certs/server.key)
CONSUL_AGENT_CERT=$(cert_cat cf-release/consul-certs/agent.crt)
CONSUL_AGENT_KEY=$(cert_cat cf-release/consul-certs/agent.key)

rm -rf keys/*
keygen jwt
JWT_VERIFICATION_KEY=$(cert_cat keys/jwt_id_rsa)
JWT_SIGNING_KEY=$(cert_cat keys/jwt_id_rsa.pub)


echo -n "Writing yaml: "
cat << EOF > cf-stub.yaml
<%
director_uuid           = '$DIRECTOR_UUID'
environment             = '$ENVIRONMENT'
floating_ip             = '$HAPROXY'
root_domain             = '$DOMAIN'
public_net_id           = '$PUBLIC_NET'
private_net_id          = '$PRIVATE_NET'
deployment_name         = 'cf'
cf_release              = '$CF_RELEASE'
protocol                = 'http'
common_password         = 'c1oudc0w'
db_enc_key              = '$DB_ENCRYPTION_KEY'
staging_upload_password = '$STAGING_UPLOAD_PASSWORD'
bulk_api_password       = '$BULK_API_PASSWORD'
blobstore_password      = '$BLOBSTORE_PASSWORD'
nats_password           = '$NATS_PASSWORD'
router_password         = '$ROUTER_PASSWORD'
ccdb_password           = '$CCDB_PASSWORD'
uaadb_password          = '$UAADB_PASSWORD'
ccdb_password           = '$CCDB_PASSWORD'
uaadb_password          = '$UAADB_PASSWORD'
consul_enc_key		= '$CONSUL_ENCRYPT_KEY'
loggregator_password	= '$LOGGREGATOR_PASSWORD'
router_password		= '$ROUTER_PASSWORD'
admin_secret 		= '$ADMIN_SECRET'
admin_secret 		= '$ADMIN_PASSWORD'
cc_client_secret 	= '$CC_CLIENT_SECRET'
cc_routing_secret 	= '$CC_ROUTING_SECRET'
cc_lookup_secret 	= '$CC_LOOKUP_SECRET '
doppler_secret 		= '$DOPPLER_SECRET'
gorouter_secret 	= '$GOROUTER_SECRET'
tcp_emitter_secret 	= '$TCP_EMITTER_SECRET'
tcp_router_secret 	= '$TCP_ROUTER_SECRET'
login_client_secret 	= '$LOGIN_CLIENT_SECRET'
n_client_secret 	= '$N_CLIENT_SECRET'

%>
---
director_uuid: <%= director_uuid %>

meta:
  environment: <%= environment %>

  floating_static_ips:
  - <%= floating_ip %>

networks:
  - name: public
    type: vip
    cloud_properties:
      net_id: <%= public_net_id %>
      security_groups: []
  - name: cf-private
    type: manual
    subnets:
    - range: 10.10.10.0/24
      gateway: 10.10.1.1
      reserved:
      - 10.10.10.2 - 10.10.10.100
      - 10.10.10.200 - 10.10.10.254
      dns:
      - 8.8.8.8
      static:
      - 10.10.10.125 - 10.10.10.175
      cloud_properties:
        net_id: <%= private_net_id %>
        security_groups: ["cf"]
  - name: cf2
    type: manual
    subnets: (( networks.cf1.subnets )) # cf2 unused by default with the OpenStack template
                                        # but the general upstream templates require this
                                        # to be a semi-valid value, so just copy cf1

properties:
  domain: <%= root_domain %>
  system_domain: <%= root_domain %>
  system_domain_organization: cf-root-domain
  app_domains: <%= root_domain %>
   - <%= root_domain %>

  ssl:
    skip_cert_verify: true

  cc:
    staging_upload_user: staging_upload_user
    staging_upload_password: <%= staging_upload_password %>
    bulk_api_password: <%= bulk_api_password %>
    db_encryption_key: <%= db_enc_key %>
    uaa_skip_ssl_validation: true

  blobstore:
    admin_users:
      - username: blobstore_user
        password: <%= blobstore_password %>
    secure_link:
      secret: blobstore-secret
    tls:
      port: 443
      cert: |
$BLOBSTORE_TLS_CERT
      private_key: |
$BLOBSTORE_PRIVATE_KEY

  consul:
    encrypt_keys:
      - <%= consul_enc_key %>
    ca_cert: |
$CONSUL_CA_CERT
    server_cert: |
$CONSUL_SERVER_CERT
    server_key: |
$CONSUL_SERVER_KEY
    agent_cert: |
$CONSUL_AGENT_CERT
    agent_key: |
$CONSUL_AGENT_KEY

  dea_next:
    disk_mb: 2048
    memory_mb: 1024
  loggregator_endpoint:
    shared_secret: <%= loggregator_password %>
  login:
    protocol: http
  nats:
    user: nats_user
    password: <%= nats_password %>
  router:
    status:
      user: router_user
      password: <%= router_password %>
  uaa:
    admin:
      client_secret: <%= admin_secret %>
    cc:
      client_secret: <%= cc_client_secret %>
    clients:
      cc_routing:
        secret: <%= cc_routing_secret %>
      cloud_controller_username_lookup:
        secret: <%= cc_lookup_secret %>
      doppler:
        secret: <%= doppler_secret %>
      gorouter:
        secret: <%= gorouter_secret %>
      tcp_emitter:
        secret: <%= tcp_emitter_secret %>
      tcp_router:
        secret: <%= tcp_router_secret %>
      login:
        secret: <%= login_client_secret %>
      notifications:
        secret: <%= n_client_secret %>
    jwt:
      verification_key: |
$JWT_VERIFICATION_KEY
      signing_key: |
$JWT_SIGNING_KEY
    scim:
      users:
        - admin|<%= ADMIN_PASSWORD %>|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose

  ccdb:
    roles:
    - name: ccadmin
      password: <%= CCDB_PASSWORD %>
  uaadb:
    roles:
    - name: uaaadmin
      password: UAADB_PASSWORD %>
  databases:
    roles:
    - name: ccadmin
      password: <%= CCDB_PASSWORD %>
    - name: uaaadmin
      password: <%= UAADB_PASSWORD %>

jobs:
  - name: ha_proxy_z1
    networks:
      - name: cf1
        default:
        - dns
        - gateway
    properties:
      ha_proxy:
        ssl_pem: |
$HAPROXY_PRIVATE_KEY
$HAPROXY_TLS_CERT
  - name: api_z1
    templates:
      - name: go-buildpack
        release: cf
      - name: binary-buildpack
        release: cf
      - name: nodejs-buildpack
        release: cf
      - name: ruby-buildpack
        release: cf
      - name: php-buildpack
        release: cf
      - name: python-buildpack
        release: cf
      - name: staticfile-buildpack
        release: cf
      - name: cloud_controller_ng
        release: cf
      - name: cloud_controller_clock
        release: cf
      - name: cloud_controller_worker
        release: cf
      - name: metron_agent
        release: cf
      - name: statsd-injector
        release: cf
      - name: route_registrar
        release: cf

  - name: api_worker_z1
    instances: 0
  - name: clock_global
    instances: 0

EOF
sleep 1;
echo "Ok"
